# Generated by Django 5.0.3 on 2024-04-11 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SharingFiles',
            fields=[
                ('share_id', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('extension', models.CharField(max_length=10)),
                ('file_id', models.IntegerField()),
                ('share_by', models.CharField(max_length=255)),
                ('share_to', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'share_files',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='FileDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=50)),
                ('extension', models.CharField(max_length=50)),
                ('upload_date', models.DateField()),
                ('path', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drive.users')),
            ],
            options={
                'db_table': 'file_details',
            },
        ),
    ]
