# Generated by Django 5.0.3 on 2024-04-19 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0002_remove_sharingfiles_file_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filedetails',
            old_name='id',
            new_name='file_id',
        ),
        migrations.RenameField(
            model_name='filedetails',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AlterModelTable(
            name='users',
            table='users',
        ),
    ]
