# Generated by Django 5.0.3 on 2024-04-05 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0002_folder'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=50)),
                ('extension', models.CharField(max_length=50)),
                ('upload_date', models.DateField()),
                ('path', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drive.users')),
            ],
            options={
                'db_table': 'file_details',
            },
        ),
        migrations.DeleteModel(
            name='Folder',
        ),
    ]
