# Generated by Django 5.0.3 on 2024-04-19 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0003_rename_id_filedetails_file_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharingfiles',
            name='file_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drive.filedetails'),
        ),
    ]
