# Generated by Django 5.0.3 on 2024-04-11 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0003_filedetails_delete_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedetails',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='SharingFiles',
            fields=[
                ('sharing_id', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('share_by', models.CharField(max_length=255)),
                ('share_to', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('file_id', models.ForeignKey(db_column='file_id', on_delete=django.db.models.deletion.CASCADE, to='drive.filedetails')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drive.users')),
            ],
            options={
                'db_table': 'sharing_files',
            },
        ),
    ]
