# Generated by Django 5.0.3 on 2024-04-19 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0004_sharingfiles_file_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filedetails',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='sharingfiles',
            old_name='file_id',
            new_name='file',
        ),
    ]
