# Generated by Django 5.0.3 on 2024-04-11 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0004_alter_filedetails_id_sharingfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharingfiles',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='drive.users'),
        ),
    ]
