# Generated by Django 5.0.3 on 2024-04-20 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0006_alter_filedetails_path_alter_sharingfiles_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedetails',
            name='path',
            field=models.TextField(),
        ),
    ]
