# Generated by Django 5.0.3 on 2024-04-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0007_alter_filedetails_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='filedetails',
            name='key',
            field=models.CharField(default='', max_length=255),
        ),
    ]
