# Generated by Django 5.0.3 on 2024-04-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0008_filedetails_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedetails',
            name='key',
            field=models.BinaryField(max_length=255),
        ),
    ]
