# Generated by Django 5.0.3 on 2024-05-05 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0011_remove_admin_firstname_remove_admin_lastname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
